export const DASHBOARD_FETCH_DATA = 'DASHBOARD_FETCH_DATA';
export const DASHBOARD_SET_LOADING = 'DASHBOARD_SET_LOADING';
export const DASHBOARD_SET_ERROR = 'DASHBOARD_SET_ERROR';
export const DASHBOARD_SET_DATA = 'DASHBOARD_SET_DATA';
