export const RESOURCES_FETCH_PAGE = 'RESOURCES_FETCH_PAGE';
export const RESOURCES_SET_LOADING = 'RESOURCES_SET_LOADING';
export const RESOURCES_SET_ERROR = 'RESOURCES_SET_ERROR';
export const RESOURCES_SET_DATA = 'RESOURCES_SET_DATA';
export const RESOURCES_SEARCH = 'RESOURCES_SEARCH';
export const RESOURCES_SET_SEARCH_RESULTS = 'RESOURCES_SET_SEARCH_RESULTS';
