export const AUTH_GET_INSTALL_URL = 'AUTH_GET_INSTALL_URL';
export const AUTH_SET_INSTALL_URL = 'AUTH_INSTALL_URL';
export const AUTH_SET_INSTALL_ERROR = 'AUTH_INSTALL_ERROR';
export const AUTH_SET_ERROR = 'AUTH_ERROR';
export const AUTH_SET_LOADING = 'AUTH_LOADING';
export const AUTH_SET_DATA = 'AUTH_DATA';
